name: 'Conftest OPA test runner'
description: 'Run OPA (rego) tests'
author: 'ibiqlik'

inputs:
  path:
    description: "Path to resources/chart that will be tested"
    required: true
  policy:
    description: "Path to policy folder. Defaults to policy"
    default: "policy"
  namespace:
    description: "Rego namespace used for testing"
    default: "main"
  output:
    description: "Output format"
    default: "stdout"
  pull_image:
    description: "Registry to pull policies from. E.g. myregistry.azurecr.io/myopapolicies:sha"
  helm:
    description: 'Bool: true|false, if testing helm charts'
    default: "false"

runs:
  using: 'docker'
  image: 'docker://ilirbekteshi/conftest-action-docker'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.policy }}
    - ${{ inputs.namespace }}
    - ${{ inputs.output }}
    - ${{ inputs.pull_image }}
    - ${{ inputs.helm }}
